language: java
services:
  - docker
sudo: required
branches:
  only:
    - master
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
script:
  - cd ispogsecbob-admin
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - docker build . -t "mikeyboom/ispogsecbob:latest"
before_install:
  - openssl aes-256-cbc -K $encrypted_1687bb340939_key -iv $encrypted_1687bb340939_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host $SERVER_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
  - docker login -u=$DOCKER_NAME -p="$DOKCER_PWD"
  - docker push mikeyboom/ispogsecbob:latest
  - chmod 600 ~/.ssh/id_rsa
  - rsync -az --delete ./docker-compose.yml root@$SERVER_IP:ispogsecbob/
  - ssh -o "StrictHostKeyChecking no" -i id_rsa root@$SERVER_IP "cd ispogsecbob/;docker-compose -f docker-compose.yml pull;docker-compose -f docker-compose.yml up -d;exit"